version: '3.8'
services:  
  php:
    image: php:8.3-apache
    container_name: php83apache
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.2
    container_name: mysql82
    restart: always
    ports:
      - "6033:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: NetStream
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
    # command: --init-file=/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin52
    depends_on:
      - mysql
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1