version: '3.8'
services:  
  mysql:
    image : mysql:8.2
    container_name: mysql
    restart: always
    ports:
      - "6033:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: db
    volumes:
      - ./:/var/lib/mysql
      - ./netstream.sql:/var/lib/mysql

  phpmyadmin:
    image : phpmyadmin:5.2
    container_name: phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1